### ISSUE TITLE
It is posible for pmsm servo? 

### ISSUE THREAD

**Issue by artayasa** [Tenebryo/servo-firmware-b-g431-esc1#1]
I have pmsm servo 200v with 2000ppr ABZ encoder. It posible to used, so for the power and driver i can coustem for the stm32 i want to used stm32f401 or 411(blackpill) it posible??? 
I was email u also sir.

**Comment by Tenebryo** [comment]
A lot of the code is specific to the B-G431-ESC driver board and the stm32g431, so it won't work for a custom driver. 

The code works with ABZ encoders, but you probably need to change some constants to calibrate it for 2000ppr (I haven't worked on this code in a while, so I don't really remember exactly which constants you would need to change).

**Comment by artayasa** [comment]
> A lot of the code is specific to the B-G431-ESC driver board and the stm32g431, so it won't work for a custom driver.
> 
> The code works with ABZ encoders, but you probably need to change some constants to calibrate it for 2000ppr (I haven't worked on this code in a while, so I don't really remember exactly which constants you would need to change).

Oh oke sir, i will try to used b g431 esc1 first, afterthat mylaybe i will make the bih board for my motor with stm32g431. And wich pin are step/dir/enable on uart sir?? Rx, tx, pwm??? Or i can see this from the cube mx??. 
Thank u for your great project, i realy apriciate for this, because i want to make coustem pmsm driver for my cnc or 3dprinter with step/dir sir. One more thank u. And this is very precision sir?? Or still have bug as long u try sir??
